with(document) {
write("<v:group id=\"group100\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:144px;\" coordsize=\"475,144\">");
write("<v:rect id=\"rect100\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:144px;\">");
write("<img id=\"img100\" name=\"PrtImgId\" src=\"../img/SEA6EP40000000K0011BAHD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:144px;border-color:#ffffff\">");
write("<p id=\"p100_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:33px;top:30px;font-weight:normal;font-size:10.56pt;\">");
write("<nobr><b>JHM<br></b></nobr>");
write("</p>");
write("<p id=\"p100_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:30px;font-weight:normal;font-size:10.56pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p100_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:30px;font-weight:normal;font-size:10.56pt;\">");
write("<nobr><b>200001<br></b></nobr>");
write("</p>");
write("<p id=\"p100_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:30px;font-weight:normal;font-size:10.56pt;\">");
write("<nobr><b>CN1<br></b></nobr>");
write("</p>");
write("<p id=\"p100_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152px;top:30px;font-weight:normal;font-size:10.56pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p100_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174px;top:30px;font-weight:normal;font-size:10.56pt;\">");
write("<nobr><b>0<br></b></nobr>");
write("</p>");
write("<p id=\"p100_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:30px;font-weight:normal;font-size:10.56pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p100_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:30px;font-weight:normal;font-size:10.56pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p100_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:27px;top:95px;font-weight:normal;font-size:14.07pt;\">");
write("<nobr><b>a<br></b></nobr>");
write("</p>");
write("<p id=\"p100_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:75px;top:95px;font-weight:normal;font-size:14.07pt;\">");
write("<nobr><b>b<br></b></nobr>");
write("</p>");
write("<p id=\"p100_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:123px;top:95px;font-weight:normal;font-size:14.07pt;\">");
write("<nobr><b>c<br></b></nobr>");
write("</p>");
write("<p id=\"p100_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:146px;top:95px;font-weight:normal;font-size:14.07pt;\">");
write("<nobr><b>d<br></b></nobr>");
write("</p>");
write("<p id=\"p100_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:95px;font-weight:normal;font-size:14.07pt;\">");
write("<nobr><b>e<br></b></nobr>");
write("</p>");
write("<p id=\"p100_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:95px;font-weight:normal;font-size:14.07pt;\">");
write("<nobr><b>f<br></b></nobr>");
write("</p>");
write("<p id=\"p100_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219px;top:95px;font-weight:normal;font-size:14.07pt;\">");
write("<nobr><b>g<br></b></nobr>");
write("</p>");
write("<p id=\"p100_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:245px;top:95px;font-weight:normal;font-size:14.07pt;\">");
write("<nobr><b>h<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}
